layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  dribbble: aelbialy
  hackerrank: ahmedletta
  instagram: a7med_del_b
  linkedin: ahmed-el-bialy-b870b6a2
  medium: ahmedelbialydev
  stackoverflow: 9138748
  telegram: mr_ahmed_e
# twitter: your_username
# website: http://your_website_url
# youtube: your_username

topics:
- name: Android
  web_url: https://github.com/topics/android
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/android/android.png  

- name: Angular
  web_url: https://github.com/topics/angular
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png
  
- name: C#
  web_url: https://github.com/topics/csharp
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/csharp/csharp.png

- name: dotnet
  web_url: https://github.com/topics/dotnet
  image_url: https://raw.githubusercontent.com/github/explore/93d8a67084f94b2a444e510199a6e7622e5b09a3/topics/dotnet/dotnet.png

- name: Firebase
  web_url: https://github.com/topics/firebase
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/firebase/firebase.png

- name: Git
  web_url: https://github.com/topics/git
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png

- name: HTML
  web_url: https://github.com/topics/html
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/html/html.png

- name: iOS
  web_url: https://github.com/topics/ios
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ios/ios.png

- name: Javascript
  web_url: https://github.com/topics/javascript
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png

- name: Kotlin
  web_url: https://github.com/topics/kotlin
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kotlin/kotlin.png

- name: Objective-C
  web_url: https://github.com/topics/objective-c
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/objective-c/objective-c.png

- name: Python
  web_url: https://github.com/topics/python
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

- name: Swift
  web_url: https://github.com/topics/swift
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png

- name: TypeScript
  web_url: https://github.com/topics/typescript
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png

- name: Xamarin
  web_url: https://github.com/topics/xamarin
  image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/xamarin/xamarin.png

  
